server:
  port: 8081

spring:
  application:
    name: microservice-auth-paylink
  datasource:
    url: jdbc:postgresql://localhost:5432/paylink_auth
    username: postgres
    password: miguel1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
         format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: ${JWT_PASSWORD}
  expiration: 86400000 # 1 día en ms